from collections import defaultdict

class Atomos:

    """Represetação Básica da Classe Atomos"""

    propriedades = [
        {"nome": "Hidrogênio", "sigla": "H", "massa atômica": 1.008},
        {"nome": "Hélio", "sigla": "He", "massa atômica": 4.003},
        {"nome": "Lítio", "sigla": "Li", "massa atômica": 6.941},
        {"nome": "Berílio", "sigla": "Be", "massa atômica": 9.012},
        {"nome": "Boro", "sigla": "B", "massa atômica": 10.81},
        {"nome": "Carbono", "sigla": "C", "massa atômica": 12.01},
        {"nome": "Nitrogênio", "sigla": "N", "massa atômica": 14.01},
        {"nome": "Oxigênio", "sigla": "O", "massa atômica": 16.00},
        {"nome": "Flúor", "sigla": "F", "massa atômica": 19.00},
        {"nome": "Neônio", "sigla": "Ne", "massa atômica": 20.18},
        {"nome": "Sódio", "sigla": "Na", "massa atômica": 22.99},
        {"nome": "Magnésio", "sigla": "Mg", "massa atômica": 24.31},
        {"nome": "Alumínio", "sigla": "Al", "massa atômica": 26.98},
        {"nome": "Silício", "sigla": "Si", "massa atômica": 28.09},
        {"nome": "Fósforo", "sigla": "P", "massa atômica": 30.97},
        {"nome": "Enxofre", "sigla": "S", "massa atômica": 32.065},
        {"nome": "Cloro", "sigla": "Cl", "massa atômica": 35.45},
        {"nome": "Argon", "sigla": "Ar", "massa atômica": 39.95},
        {"nome": "Potássio", "sigla": "K", "massa atômica": 39.10},
        {"nome": "Cálcio", "sigla": "Ca", "massa atômica": 40.08},
        {"nome": "Escândio", "sigla": "Sc", "massa atômica": 44.96},
        {"nome": "Titânio", "sigla": "Ti", "massa atômica": 47.87},
        {"nome": "Vanádio", "sigla": "V", "massa atômica": 50.94},
        {"nome": "Crômio", "sigla": "Cr", "massa atômica": 52.00},
        {"nome": "Manganês", "sigla": "Mn", "massa atômica": 54.94},
        {"nome": "Ferro", "sigla": "Fe", "massa atômica": 55.85},
        {"nome": "Cobalto", "sigla": "Co", "massa atômica": 58.93},
        {"nome": "Níquel", "sigla": "Ni", "massa atômica": 58.69},
        {"nome": "Cobre", "sigla": "Cu", "massa atômica": 63.55},
        {"nome": "Zinco", "sigla": "Zn", "massa atômica": 65.38},
        {"nome": "Galio", "sigla": "Ga", "massa atômica": 69.72},
        {"nome": "Germânio", "sigla": "Ge", "massa atômica": 72.63},
        {"nome": "Arsênio", "sigla": "As", "massa atômica": 74.92},
        {"nome": "Selénio", "sigla": "Se", "massa atômica":78.96},
        {"nome": "Bromo", "sigla": "Br", "massa atômica":79.90},
        {"nome": "Krípton", "sigla": "Kr", "massa atômica":83.79},
        {"nome": "Rubídio", "sigla": "Rb", "massa atômica":85.46},
        {"nome": "Estrôncio", "sigla": "Sr", "massa atômica":87.62},
        {"nome": "Ítrio", "sigla": "Y", "massa atômica":88.90},
        {"nome": "Zircônio", "sigla": "Zr", "massa atômica":91.22},
        {"nome": "Nióbio", "sigla": "Nb", "massa atômica":92.90},
        {"nome": "Molibdénio", "sigla": "Mo", "massa atômica":95.95},
        {"nome": "Tecnécio", "sigla": "Tc", "massa atômica":98},
        {"nome": "Rutênio", "sigla": "Ru", "massa atômica":101.07},
        {"nome": "Ródio", "sigla": "Rh", "massa atômica":102.91},
        {"nome": "Paládio", "sigla": "Pd", "massa atômica":106.42},
        {"nome": "Prata", "sigla": "Ag", "massa atômica":107.87},
        {"nome": "Cádmio", "sigla": "Cd", "massa atômica":112.41},
        {"nome": "Índio", "sigla": "In", "massa atômica":114.82},
        {"nome": "Estanho", "sigla": "Sn", "massa atômica":118.71},
        {"nome": "Antimônio", "sigla": "Sb", "massa atômica": 121.76},
        {"nome": "Telúrio", "sigla": "Te", "massa atômica": 127.60},
        {"nome": "Iodeto", "sigla": "I", "massa atômica": 126.9},
        {"nome": "Xenônio", "sigla": "Xe", "massa atômica": 131.29},
        {"nome": "Cesio", "sigla": "Cs", "massa atômica": 132.91},
        {"nome": "Bario", "sigla": "Ba", "massa atômica": 137.33},
        {"nome": "Lantânio", "sigla": "La", "massa atômica": 138.91},
        {"nome": "Cerio", "sigla": "Ce", "massa atômica": 140.12},
        {"nome": "Praseodímio", "sigla": "Pr", "massa atômica": 140.91},
        {"nome": "Neodímio", "sigla": "Nd", "massa atômica": 144.24},
        {"nome": "Promécio", "sigla": "Pm", "massa atômica": 145.0},
        {"nome": "Samário", "sigla": "Sm", "massa atômica": 150.36},
        {"nome": "Europio", "sigla": "Eu", "massa atômica": 152.0},
        {"nome": "Gadolínio", "sigla": "Gd", "massa atômica": 157.25},
        {"nome": "Terbio", "sigla": "Tb", "massa atômica": 158.93},
        {"nome": "Disprósio", "sigla": "Dy", "massa atômica": 162.50},
        {"nome": "Holmio", "sigla": "Ho", "massa atômica": 164.93},
        {"nome": "Erbio", "sigla": "Er", "massa atômica": 167.26},
        {"nome": "Tulério", "sigla": "Tm", "massa atômica": 168.93},
        {"nome": "Iterbio", "sigla": "Yb", "massa atômica": 173.04},
        {"nome": "Lutécio", "sigla": "Lu", "massa atômica": 175.0},
        {"nome": "Hafnio", "sigla": "Hf", "massa atômica": 178.49},
        {"nome": "Tântalo", "sigla": "Ta", "massa atômica": 180.95},
        {"nome": "Tungstênio", "sigla": "W", "massa atômica": 183.84},
        {"nome": "Rênio", "sigla": "Re", "massa atômica": 186.21},
        {"nome": "Ósmio", "sigla": "Os", "massa atômica": 190.23},
        {"nome": "Irídio", "sigla": "Ir", "massa atômica": 192.22},
        {"nome": "Platina", "sigla": "Pt", "massa atômica": 195.08},
        {"nome": "Ouro", "sigla": "Au", "massa atômica":196.97},
        {"nome": "Mercúrio", "sigla": "Hg", "massa atômica": 200.59},
        {"nome": "Tálio", "sigla": "Tl", "massa atômica": 204.38},
        {"nome": "Chumbo", "sigla": "Pb", "massa atômica": 207.2},
        {"nome": "Bismuto", "sigla": "Bi", "massa atômica": 209.0},
        {"nome": "Polônio", "sigla": "Po", "massa atômica": 209.0},
        {"nome": "Astato", "sigla": "At", "massa atômica": 210.0},
        {"nome": "Radônio", "sigla": "Rn", "massa atômica": 222.0},
        {"nome": "Frâncio", "sigla": "Fr", "massa atômica": 223.0},
        {"nome": "Radium", "sigla": "Ra", "massa atômica": 226.0},
        {"nome": "Actínio", "sigla": "Ac", "massa atômica": 227.0},
        {"nome": "Tório", "sigla": "Th", "massa atômica": 232.04},
        {"nome": "Protactínio", "sigla": "Pa", "massa atômica": 231.04},
        {"nome": "Urano", "sigla": "U", "massa atômica": 238.03},
        {"nome": "Neptúnio", "sigla": "Np", "massa atômica": 237.0},
        {"nome": "Plutônio", "sigla": "Pu", "massa atômica": 244.0},
        {"nome": "Amerício", "sigla": "Am", "massa atômica": 243.0},
        {"nome": "Curio", "sigla": "Cm", "massa atômica": 247.0},
        {"nome": "Berquélio", "sigla": "Bk", "massa atômica": 247.0},
        {"nome": "Califórnio", "sigla": "Cf", "massa atômica": 251.0},
        {"nome": "Einstênio", "sigla": "Es", "massa atômica": 252.0},
        {"nome": "Férmio", "sigla": "Fm", "massa atômica": 257.0},
        {"nome": "Mendelévio", "sigla": "Md", "massa atômica": 258.0},
        {"nome": "Nobélio", "sigla": "No", "massa atômica": 259},
        {"nome": "Laurêncio", "sigla": "Lr", "massa atômica": 262.0},
        {"nome": "Rutherfórdio", "sigla": "Rf", "massa atômica": 261.0},
        {"nome": "Dubnium", "sigla": "Db", "massa atômica": 262.0},
        {"nome": "Seabórgio", "sigla": "Sg", "massa atômica": 266.0},
        {"nome": "Bóhrio", "sigla": "Bh", "massa atômica": 264.0},
        {"nome": "Hássio", "sigla": "Hs", "massa atômica": 277.0},
        {"nome": "Meitnério", "sigla": "Mt", "massa atômica": 268.0},
        {"nome": "Darmstádio", "sigla": "Ds", "massa atômica": 281.0},
        {"nome": "Roentgênio", "sigla": "Rg", "massa atômica": 280.0},
        {"nome": "Copernício", "sigla": "Cn", "massa atômica": 285.0},
        {"nome": "Nihônio", "sigla": "Nh", "massa atômica": 286.0},
        {"nome": "Fleróvio", "sigla": "Fl", "massa atômica": 289.0},
        {"nome": "Moscóvio", "sigla": "Mc", "massa atômica": 289.0},
        {"nome": "Livermório", "sigla": "Lv", "massa atômica": 293.0},
        {"nome": "Tennessine", "sigla": "Ts", "massa atômica": 294.0},
        {"nome": "Oganessônio", "sigla": "Og", "massa atômica": 294.0},
    ]


if __name__ == "__main__":
    print(Atomos.propriedades)